sudo: false
language: node_js
node_js:
  - 16 # use nodejs v16 LTS
cache: npm
branches:
  only:
    - source # build hexo branch only
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    all_branches: true # solve a permission problem
  target_branch: master
  local-dir: public